# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roman Vyškovský
email: vyskovskyroman@gmail.com
description: Specialista na On-line marketing se zaměřením na PPC
logo: "/assets/images/logoRV.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vyskovskyroman.eu" # the base hostname & protocol for your site

  
name: 'Roman Vyškovský'
bio: Specialista na On-line marketing se zaměřením na PPC
author_image: "/assets/images/author.jpg"
twitter_username: RVyskovsky

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  
github: [metadata]
